package statemgmt

import (
	"fmt"

	"github.com/golang/protobuf/proto"
	"github.com/op/go-logging"
)

var mgmtLogger = logging.MustGetLogger("txset_statemgmt")

// Bytes returns this block as an array of bytes.
func (txStateValue *TxSetStateValue) Bytes() ([]byte, error) {
	data, err := proto.Marshal(txStateValue)
	if err != nil {
		mgmtLogger.Errorf("Error marshalling txSetStateValue: %s", err)
		return nil, fmt.Errorf("Could not marshal txSetStateValue: %s", err)
	}
	return data, nil
}

// UnmarshallTxSetStateValue converts a byte array generated by Bytes() back to a block.
func UnmarshallTxSetStateValue(marshalledState []byte) (*TxSetStateValue, error) {
	stateValue := &TxSetStateValue{}
	err := proto.Unmarshal(marshalledState, stateValue)
	if err != nil {
		mgmtLogger.Errorf("Error unmarshalling txSetStateValue: %s", err)
		return nil, fmt.Errorf("Could not unmarshal txSetStateValue: %s", err)
	}
	return stateValue, nil
}

