// Code generated by protoc-gen-go.
// source: blockchainmessages.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Confidentiality Levels
type ConfidentialityLevel int32

const (
	ConfidentialityLevel_PUBLIC       ConfidentialityLevel = 0
	ConfidentialityLevel_CONFIDENTIAL ConfidentialityLevel = 1
)

var ConfidentialityLevel_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}
var ConfidentialityLevel_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ConfidentialityLevel) String() string {
	return proto.EnumName(ConfidentialityLevel_name, int32(x))
}
func (ConfidentialityLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ChaincodeAction int32

const (
	ChaincodeAction_UNDEFINED ChaincodeAction = 0
	// deploy a chaincode to the network and call `Init` function
	ChaincodeAction_CHAINCODE_DEPLOY ChaincodeAction = 1
	// call a chaincode `Invoke` function as a transaction
	ChaincodeAction_CHAINCODE_INVOKE ChaincodeAction = 2
	// call a chaincode `query` function
	ChaincodeAction_CHAINCODE_QUERY ChaincodeAction = 3
	// terminate a chaincode; not implemented yet
	ChaincodeAction_CHAINCODE_TERMINATE ChaincodeAction = 4
)

var ChaincodeAction_name = map[int32]string{
	0: "UNDEFINED",
	1: "CHAINCODE_DEPLOY",
	2: "CHAINCODE_INVOKE",
	3: "CHAINCODE_QUERY",
	4: "CHAINCODE_TERMINATE",
}
var ChaincodeAction_value = map[string]int32{
	"UNDEFINED":           0,
	"CHAINCODE_DEPLOY":    1,
	"CHAINCODE_INVOKE":    2,
	"CHAINCODE_QUERY":     3,
	"CHAINCODE_TERMINATE": 4,
}

func (x ChaincodeAction) String() string {
	return proto.EnumName(ChaincodeAction_name, int32(x))
}
func (ChaincodeAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ChaincodeSpec_Type int32

const (
	ChaincodeSpec_UNDEFINED ChaincodeSpec_Type = 0
	ChaincodeSpec_GOLANG    ChaincodeSpec_Type = 1
	ChaincodeSpec_NODE      ChaincodeSpec_Type = 2
	ChaincodeSpec_CAR       ChaincodeSpec_Type = 3
	ChaincodeSpec_JAVA      ChaincodeSpec_Type = 4
)

var ChaincodeSpec_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "GOLANG",
	2: "NODE",
	3: "CAR",
	4: "JAVA",
}
var ChaincodeSpec_Type_value = map[string]int32{
	"UNDEFINED": 0,
	"GOLANG":    1,
	"NODE":      2,
	"CAR":       3,
	"JAVA":      4,
}

func (x ChaincodeSpec_Type) String() string {
	return proto.EnumName(ChaincodeSpec_Type_name, int32(x))
}
func (ChaincodeSpec_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

type TxSetSpec_Type int32

const (
	TxSetSpec_CREATION  TxSetSpec_Type = 0
	TxSetSpec_EXTENSION TxSetSpec_Type = 1
)

var TxSetSpec_Type_name = map[int32]string{
	0: "CREATION",
	1: "EXTENSION",
}
var TxSetSpec_Type_value = map[string]int32{
	"CREATION":  0,
	"EXTENSION": 1,
}

func (x TxSetSpec_Type) String() string {
	return proto.EnumName(TxSetSpec_Type_name, int32(x))
}
func (TxSetSpec_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5, 0} }

type ChaincodeDeploymentSpec_ExecutionEnvironment int32

const (
	ChaincodeDeploymentSpec_DOCKER ChaincodeDeploymentSpec_ExecutionEnvironment = 0
	ChaincodeDeploymentSpec_SYSTEM ChaincodeDeploymentSpec_ExecutionEnvironment = 1
)

var ChaincodeDeploymentSpec_ExecutionEnvironment_name = map[int32]string{
	0: "DOCKER",
	1: "SYSTEM",
}
var ChaincodeDeploymentSpec_ExecutionEnvironment_value = map[string]int32{
	"DOCKER": 0,
	"SYSTEM": 1,
}

func (x ChaincodeDeploymentSpec_ExecutionEnvironment) String() string {
	return proto.EnumName(ChaincodeDeploymentSpec_ExecutionEnvironment_name, int32(x))
}
func (ChaincodeDeploymentSpec_ExecutionEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{7, 0}
}

type ChaincodeMessage_Type int32

const (
	ChaincodeMessage_UNDEFINED               ChaincodeMessage_Type = 0
	ChaincodeMessage_REGISTER                ChaincodeMessage_Type = 1
	ChaincodeMessage_REGISTERED              ChaincodeMessage_Type = 2
	ChaincodeMessage_INIT                    ChaincodeMessage_Type = 3
	ChaincodeMessage_READY                   ChaincodeMessage_Type = 4
	ChaincodeMessage_TRANSACTION             ChaincodeMessage_Type = 5
	ChaincodeMessage_COMPLETED               ChaincodeMessage_Type = 6
	ChaincodeMessage_ERROR                   ChaincodeMessage_Type = 7
	ChaincodeMessage_GET_STATE               ChaincodeMessage_Type = 8
	ChaincodeMessage_PUT_STATE               ChaincodeMessage_Type = 9
	ChaincodeMessage_DEL_STATE               ChaincodeMessage_Type = 10
	ChaincodeMessage_INVOKE_CHAINCODE        ChaincodeMessage_Type = 11
	ChaincodeMessage_INVOKE_QUERY            ChaincodeMessage_Type = 12
	ChaincodeMessage_RESPONSE                ChaincodeMessage_Type = 13
	ChaincodeMessage_QUERY                   ChaincodeMessage_Type = 14
	ChaincodeMessage_QUERY_COMPLETED         ChaincodeMessage_Type = 15
	ChaincodeMessage_QUERY_ERROR             ChaincodeMessage_Type = 16
	ChaincodeMessage_RANGE_QUERY_STATE       ChaincodeMessage_Type = 17
	ChaincodeMessage_RANGE_QUERY_STATE_NEXT  ChaincodeMessage_Type = 18
	ChaincodeMessage_RANGE_QUERY_STATE_CLOSE ChaincodeMessage_Type = 19
	ChaincodeMessage_KEEPALIVE               ChaincodeMessage_Type = 20
)

var ChaincodeMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "REGISTER",
	2:  "REGISTERED",
	3:  "INIT",
	4:  "READY",
	5:  "TRANSACTION",
	6:  "COMPLETED",
	7:  "ERROR",
	8:  "GET_STATE",
	9:  "PUT_STATE",
	10: "DEL_STATE",
	11: "INVOKE_CHAINCODE",
	12: "INVOKE_QUERY",
	13: "RESPONSE",
	14: "QUERY",
	15: "QUERY_COMPLETED",
	16: "QUERY_ERROR",
	17: "RANGE_QUERY_STATE",
	18: "RANGE_QUERY_STATE_NEXT",
	19: "RANGE_QUERY_STATE_CLOSE",
	20: "KEEPALIVE",
}
var ChaincodeMessage_Type_value = map[string]int32{
	"UNDEFINED":               0,
	"REGISTER":                1,
	"REGISTERED":              2,
	"INIT":                    3,
	"READY":                   4,
	"TRANSACTION":             5,
	"COMPLETED":               6,
	"ERROR":                   7,
	"GET_STATE":               8,
	"PUT_STATE":               9,
	"DEL_STATE":               10,
	"INVOKE_CHAINCODE":        11,
	"INVOKE_QUERY":            12,
	"RESPONSE":                13,
	"QUERY":                   14,
	"QUERY_COMPLETED":         15,
	"QUERY_ERROR":             16,
	"RANGE_QUERY_STATE":       17,
	"RANGE_QUERY_STATE_NEXT":  18,
	"RANGE_QUERY_STATE_CLOSE": 19,
	"KEEPALIVE":               20,
}

func (x ChaincodeMessage_Type) String() string {
	return proto.EnumName(ChaincodeMessage_Type_name, int32(x))
}
func (ChaincodeMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{10, 0} }

// ChaincodeID contains the path as specified by the deploy transaction
// that created it as well as the hashCode that is generated by the
// system for the path. From the user level (ie, CLI, REST API and so on)
// deploy transaction is expected to provide the path and other requests
// are expected to provide the hashCode. The other value will be ignored.
// Internally, the structure could contain both values. For instance, the
// hashCode will be set when first generated using the path
type ChaincodeID struct {
	// deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// all other requests will use the name (really a hashcode) generated by
	// the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ChaincodeID) Reset()                    { *m = ChaincodeID{} }
func (m *ChaincodeID) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeID) ProtoMessage()               {}
func (*ChaincodeID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// Carries the chaincode function and its arguments.
// UnmarshalJSON in transaction.go converts the string-based REST/JSON input to
// the []byte-based current ChaincodeInput structure.
type ChaincodeInput struct {
	Args [][]byte `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *ChaincodeInput) Reset()                    { *m = ChaincodeInput{} }
func (m *ChaincodeInput) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInput) ProtoMessage()               {}
func (*ChaincodeInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type TxSetInput struct {
	Type         TxSetSpec_Type               `protobuf:"varint,1,opt,name=type,enum=protos.TxSetSpec_Type" json:"type,omitempty"`
	DefaultIndex uint64                       `protobuf:"varint,2,opt,name=defaultIndex" json:"defaultIndex,omitempty"`
	SetID        string                       `protobuf:"bytes,3,opt,name=setID" json:"setID,omitempty"`
	TxSpecs      []*TxSetInput_SimplifiedSpec `protobuf:"bytes,4,rep,name=txSpecs" json:"txSpecs,omitempty"`
}

func (m *TxSetInput) Reset()                    { *m = TxSetInput{} }
func (m *TxSetInput) String() string            { return proto.CompactTextString(m) }
func (*TxSetInput) ProtoMessage()               {}
func (*TxSetInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TxSetInput) GetTxSpecs() []*TxSetInput_SimplifiedSpec {
	if m != nil {
		return m.TxSpecs
	}
	return nil
}

type TxSetInput_SimplifiedSpec struct {
	Action      ChaincodeAction    `protobuf:"varint,1,opt,name=action,enum=protos.ChaincodeAction" json:"action,omitempty"`
	Lang        ChaincodeSpec_Type `protobuf:"varint,2,opt,name=lang,enum=protos.ChaincodeSpec_Type" json:"lang,omitempty"`
	ChaincodeID *ChaincodeID       `protobuf:"bytes,3,opt,name=chaincodeID" json:"chaincodeID,omitempty"`
	InputArgs   *ChaincodeInput    `protobuf:"bytes,4,opt,name=inputArgs" json:"inputArgs,omitempty"`
	CustomIDGen string             `protobuf:"bytes,5,opt,name=customIDGen" json:"customIDGen,omitempty"`
}

func (m *TxSetInput_SimplifiedSpec) Reset()                    { *m = TxSetInput_SimplifiedSpec{} }
func (m *TxSetInput_SimplifiedSpec) String() string            { return proto.CompactTextString(m) }
func (*TxSetInput_SimplifiedSpec) ProtoMessage()               {}
func (*TxSetInput_SimplifiedSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

func (m *TxSetInput_SimplifiedSpec) GetChaincodeID() *ChaincodeID {
	if m != nil {
		return m.ChaincodeID
	}
	return nil
}

func (m *TxSetInput_SimplifiedSpec) GetInputArgs() *ChaincodeInput {
	if m != nil {
		return m.InputArgs
	}
	return nil
}

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
type ChaincodeSpec struct {
	Type                 ChaincodeSpec_Type   `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeSpec_Type" json:"type,omitempty"`
	ChaincodeID          *ChaincodeID         `protobuf:"bytes,2,opt,name=chaincodeID" json:"chaincodeID,omitempty"`
	CtorMsg              *ChaincodeInput      `protobuf:"bytes,3,opt,name=ctorMsg" json:"ctorMsg,omitempty"`
	Timeout              int32                `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	SecureContext        string               `protobuf:"bytes,5,opt,name=secureContext" json:"secureContext,omitempty"`
	ConfidentialityLevel ConfidentialityLevel `protobuf:"varint,6,opt,name=confidentialityLevel,enum=protos.ConfidentialityLevel" json:"confidentialityLevel,omitempty"`
	Metadata             []byte               `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attributes           []string             `protobuf:"bytes,8,rep,name=attributes" json:"attributes,omitempty"`
}

func (m *ChaincodeSpec) Reset()                    { *m = ChaincodeSpec{} }
func (m *ChaincodeSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeSpec) ProtoMessage()               {}
func (*ChaincodeSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ChaincodeSpec) GetChaincodeID() *ChaincodeID {
	if m != nil {
		return m.ChaincodeID
	}
	return nil
}

func (m *ChaincodeSpec) GetCtorMsg() *ChaincodeInput {
	if m != nil {
		return m.CtorMsg
	}
	return nil
}

type TxSpec struct {
	// Types that are valid to be assigned to Spec:
	//	*TxSpec_CodeSpec
	//	*TxSpec_InvocationSpec
	Spec   isTxSpec_Spec   `protobuf_oneof:"Spec"`
	Action ChaincodeAction `protobuf:"varint,3,opt,name=action,enum=protos.ChaincodeAction" json:"action,omitempty"`
}

func (m *TxSpec) Reset()                    { *m = TxSpec{} }
func (m *TxSpec) String() string            { return proto.CompactTextString(m) }
func (*TxSpec) ProtoMessage()               {}
func (*TxSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type isTxSpec_Spec interface {
	isTxSpec_Spec()
}

type TxSpec_CodeSpec struct {
	CodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=codeSpec,oneof"`
}
type TxSpec_InvocationSpec struct {
	InvocationSpec *ChaincodeInvocationSpec `protobuf:"bytes,2,opt,name=invocationSpec,oneof"`
}

func (*TxSpec_CodeSpec) isTxSpec_Spec()       {}
func (*TxSpec_InvocationSpec) isTxSpec_Spec() {}

func (m *TxSpec) GetSpec() isTxSpec_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *TxSpec) GetCodeSpec() *ChaincodeSpec {
	if x, ok := m.GetSpec().(*TxSpec_CodeSpec); ok {
		return x.CodeSpec
	}
	return nil
}

func (m *TxSpec) GetInvocationSpec() *ChaincodeInvocationSpec {
	if x, ok := m.GetSpec().(*TxSpec_InvocationSpec); ok {
		return x.InvocationSpec
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TxSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TxSpec_OneofMarshaler, _TxSpec_OneofUnmarshaler, _TxSpec_OneofSizer, []interface{}{
		(*TxSpec_CodeSpec)(nil),
		(*TxSpec_InvocationSpec)(nil),
	}
}

func _TxSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TxSpec)
	// Spec
	switch x := m.Spec.(type) {
	case *TxSpec_CodeSpec:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CodeSpec); err != nil {
			return err
		}
	case *TxSpec_InvocationSpec:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InvocationSpec); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TxSpec.Spec has unexpected type %T", x)
	}
	return nil
}

func _TxSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TxSpec)
	switch tag {
	case 1: // Spec.codeSpec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChaincodeSpec)
		err := b.DecodeMessage(msg)
		m.Spec = &TxSpec_CodeSpec{msg}
		return true, err
	case 2: // Spec.invocationSpec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChaincodeInvocationSpec)
		err := b.DecodeMessage(msg)
		m.Spec = &TxSpec_InvocationSpec{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TxSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TxSpec)
	// Spec
	switch x := m.Spec.(type) {
	case *TxSpec_CodeSpec:
		s := proto.Size(x.CodeSpec)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxSpec_InvocationSpec:
		s := proto.Size(x.InvocationSpec)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Carries the specification for a transactions set.
// It is composed by the chaincode specification of all the transactions forming the tx set
type TxSetSpec struct {
	Type TxSetSpec_Type `protobuf:"varint,1,opt,name=type,enum=protos.TxSetSpec_Type" json:"type,omitempty"`
	// bytes represet a TxSpec
	TxSpecs              [][]byte             `protobuf:"bytes,2,rep,name=txSpecs,proto3" json:"txSpecs,omitempty"`
	DefaultInx           uint64               `protobuf:"varint,3,opt,name=defaultInx" json:"defaultInx,omitempty"`
	ExtSetID             string               `protobuf:"bytes,4,opt,name=extSetID" json:"extSetID,omitempty"`
	SecureContext        string               `protobuf:"bytes,5,opt,name=secureContext" json:"secureContext,omitempty"`
	ConfidentialityLevel ConfidentialityLevel `protobuf:"varint,6,opt,name=confidentialityLevel,enum=protos.ConfidentialityLevel" json:"confidentialityLevel,omitempty"`
	Metadata             []byte               `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *TxSetSpec) Reset()                    { *m = TxSetSpec{} }
func (m *TxSetSpec) String() string            { return proto.CompactTextString(m) }
func (*TxSetSpec) ProtoMessage()               {}
func (*TxSetSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

// Carries the specification for a Mutant transaction.
type MutantSpec struct {
	TxSetID string `protobuf:"bytes,1,opt,name=txSetID" json:"txSetID,omitempty"`
	Index   uint64 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *MutantSpec) Reset()                    { *m = MutantSpec{} }
func (m *MutantSpec) String() string            { return proto.CompactTextString(m) }
func (*MutantSpec) ProtoMessage()               {}
func (*MutantSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

// Specify the deployment of a chaincode.
// TODO: Define `codePackage`.
type ChaincodeDeploymentSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincodeSpec" json:"chaincodeSpec,omitempty"`
	// Controls when the chaincode becomes executable.
	EffectiveDate *google_protobuf.Timestamp                   `protobuf:"bytes,2,opt,name=effectiveDate" json:"effectiveDate,omitempty"`
	CodePackage   []byte                                       `protobuf:"bytes,3,opt,name=codePackage,proto3" json:"codePackage,omitempty"`
	ExecEnv       ChaincodeDeploymentSpec_ExecutionEnvironment `protobuf:"varint,4,opt,name=execEnv,enum=protos.ChaincodeDeploymentSpec_ExecutionEnvironment" json:"execEnv,omitempty"`
}

func (m *ChaincodeDeploymentSpec) Reset()                    { *m = ChaincodeDeploymentSpec{} }
func (m *ChaincodeDeploymentSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeDeploymentSpec) ProtoMessage()               {}
func (*ChaincodeDeploymentSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ChaincodeDeploymentSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetEffectiveDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.EffectiveDate
	}
	return nil
}

// Carries the chaincode function and its arguments.
type ChaincodeInvocationSpec struct {
	ChaincodeSpec *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincodeSpec" json:"chaincodeSpec,omitempty"`
	// This field can contain a user-specified ID generation algorithm
	// If supplied, this will be used to generate a ID
	// If not supplied (left empty), sha256base64 will be used
	// The algorithm consists of two parts:
	//  1, a hash function
	//  2, a decoding used to decode user (string) input to bytes
	// Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
	IdGenerationAlg string `protobuf:"bytes,2,opt,name=idGenerationAlg" json:"idGenerationAlg,omitempty"`
}

func (m *ChaincodeInvocationSpec) Reset()                    { *m = ChaincodeInvocationSpec{} }
func (m *ChaincodeInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeInvocationSpec) ProtoMessage()               {}
func (*ChaincodeInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ChaincodeInvocationSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

// This structure contain transaction data that we send to the chaincode
// container shim and allow the chaincode to access through the shim interface.
// TODO: Consider remove this message and just pass the transaction object
// to the shim and/or allow the chaincode to query transactions.
type ChaincodeSecurityContext struct {
	CallerCert     []byte                     `protobuf:"bytes,1,opt,name=callerCert,proto3" json:"callerCert,omitempty"`
	CallerSign     []byte                     `protobuf:"bytes,2,opt,name=callerSign,proto3" json:"callerSign,omitempty"`
	Payload        []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Binding        []byte                     `protobuf:"bytes,4,opt,name=binding,proto3" json:"binding,omitempty"`
	Metadata       []byte                     `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ParentMetadata []byte                     `protobuf:"bytes,6,opt,name=parentMetadata,proto3" json:"parentMetadata,omitempty"`
	TxTimestamp    *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=txTimestamp" json:"txTimestamp,omitempty"`
}

func (m *ChaincodeSecurityContext) Reset()                    { *m = ChaincodeSecurityContext{} }
func (m *ChaincodeSecurityContext) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeSecurityContext) ProtoMessage()               {}
func (*ChaincodeSecurityContext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ChaincodeSecurityContext) GetTxTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.TxTimestamp
	}
	return nil
}

type ChaincodeMessage struct {
	Type            ChaincodeMessage_Type      `protobuf:"varint,1,opt,name=type,enum=protos.ChaincodeMessage_Type" json:"type,omitempty"`
	Timestamp       *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload         []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid            string                     `protobuf:"bytes,4,opt,name=txid" json:"txid,omitempty"`
	SecurityContext *ChaincodeSecurityContext  `protobuf:"bytes,5,opt,name=securityContext" json:"securityContext,omitempty"`
	// event emmited by chaincode. Used only with Init or Invoke.
	// This event is then stored (currently)
	// with Block.NonHashData.TransactionResult
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,6,opt,name=chaincodeEvent" json:"chaincodeEvent,omitempty"`
}

func (m *ChaincodeMessage) Reset()                    { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string            { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()               {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ChaincodeMessage) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChaincodeMessage) GetSecurityContext() *ChaincodeSecurityContext {
	if m != nil {
		return m.SecurityContext
	}
	return nil
}

func (m *ChaincodeMessage) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

type PutStateInfo struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutStateInfo) Reset()                    { *m = PutStateInfo{} }
func (m *PutStateInfo) String() string            { return proto.CompactTextString(m) }
func (*PutStateInfo) ProtoMessage()               {}
func (*PutStateInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type RangeQueryState struct {
	StartKey string `protobuf:"bytes,1,opt,name=startKey" json:"startKey,omitempty"`
	EndKey   string `protobuf:"bytes,2,opt,name=endKey" json:"endKey,omitempty"`
}

func (m *RangeQueryState) Reset()                    { *m = RangeQueryState{} }
func (m *RangeQueryState) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryState) ProtoMessage()               {}
func (*RangeQueryState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type RangeQueryStateNext struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *RangeQueryStateNext) Reset()                    { *m = RangeQueryStateNext{} }
func (m *RangeQueryStateNext) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateNext) ProtoMessage()               {}
func (*RangeQueryStateNext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type RangeQueryStateClose struct {
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *RangeQueryStateClose) Reset()                    { *m = RangeQueryStateClose{} }
func (m *RangeQueryStateClose) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateClose) ProtoMessage()               {}
func (*RangeQueryStateClose) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type RangeQueryStateKeyValue struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *RangeQueryStateKeyValue) Reset()                    { *m = RangeQueryStateKeyValue{} }
func (m *RangeQueryStateKeyValue) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateKeyValue) ProtoMessage()               {}
func (*RangeQueryStateKeyValue) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type RangeQueryStateResponse struct {
	KeysAndValues []*RangeQueryStateKeyValue `protobuf:"bytes,1,rep,name=keysAndValues" json:"keysAndValues,omitempty"`
	HasMore       bool                       `protobuf:"varint,2,opt,name=hasMore" json:"hasMore,omitempty"`
	ID            string                     `protobuf:"bytes,3,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *RangeQueryStateResponse) Reset()                    { *m = RangeQueryStateResponse{} }
func (m *RangeQueryStateResponse) String() string            { return proto.CompactTextString(m) }
func (*RangeQueryStateResponse) ProtoMessage()               {}
func (*RangeQueryStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *RangeQueryStateResponse) GetKeysAndValues() []*RangeQueryStateKeyValue {
	if m != nil {
		return m.KeysAndValues
	}
	return nil
}

func init() {
	proto.RegisterType((*ChaincodeID)(nil), "protos.ChaincodeID")
	proto.RegisterType((*ChaincodeInput)(nil), "protos.ChaincodeInput")
	proto.RegisterType((*TxSetInput)(nil), "protos.TxSetInput")
	proto.RegisterType((*TxSetInput_SimplifiedSpec)(nil), "protos.TxSetInput.SimplifiedSpec")
	proto.RegisterType((*ChaincodeSpec)(nil), "protos.ChaincodeSpec")
	proto.RegisterType((*TxSpec)(nil), "protos.TxSpec")
	proto.RegisterType((*TxSetSpec)(nil), "protos.TxSetSpec")
	proto.RegisterType((*MutantSpec)(nil), "protos.MutantSpec")
	proto.RegisterType((*ChaincodeDeploymentSpec)(nil), "protos.ChaincodeDeploymentSpec")
	proto.RegisterType((*ChaincodeInvocationSpec)(nil), "protos.ChaincodeInvocationSpec")
	proto.RegisterType((*ChaincodeSecurityContext)(nil), "protos.ChaincodeSecurityContext")
	proto.RegisterType((*ChaincodeMessage)(nil), "protos.ChaincodeMessage")
	proto.RegisterType((*PutStateInfo)(nil), "protos.PutStateInfo")
	proto.RegisterType((*RangeQueryState)(nil), "protos.RangeQueryState")
	proto.RegisterType((*RangeQueryStateNext)(nil), "protos.RangeQueryStateNext")
	proto.RegisterType((*RangeQueryStateClose)(nil), "protos.RangeQueryStateClose")
	proto.RegisterType((*RangeQueryStateKeyValue)(nil), "protos.RangeQueryStateKeyValue")
	proto.RegisterType((*RangeQueryStateResponse)(nil), "protos.RangeQueryStateResponse")
	proto.RegisterEnum("protos.ConfidentialityLevel", ConfidentialityLevel_name, ConfidentialityLevel_value)
	proto.RegisterEnum("protos.ChaincodeAction", ChaincodeAction_name, ChaincodeAction_value)
	proto.RegisterEnum("protos.ChaincodeSpec_Type", ChaincodeSpec_Type_name, ChaincodeSpec_Type_value)
	proto.RegisterEnum("protos.TxSetSpec_Type", TxSetSpec_Type_name, TxSetSpec_Type_value)
	proto.RegisterEnum("protos.ChaincodeDeploymentSpec_ExecutionEnvironment", ChaincodeDeploymentSpec_ExecutionEnvironment_name, ChaincodeDeploymentSpec_ExecutionEnvironment_value)
	proto.RegisterEnum("protos.ChaincodeMessage_Type", ChaincodeMessage_Type_name, ChaincodeMessage_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ChaincodeSupport service

type ChaincodeSupportClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error)
}

type chaincodeSupportClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeSupportClient(cc *grpc.ClientConn) ChaincodeSupportClient {
	return &chaincodeSupportClient{cc}
}

func (c *chaincodeSupportClient) Register(ctx context.Context, opts ...grpc.CallOption) (ChaincodeSupport_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChaincodeSupport_serviceDesc.Streams[0], c.cc, "/protos.ChaincodeSupport/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeSupportRegisterClient{stream}
	return x, nil
}

type ChaincodeSupport_RegisterClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeSupportRegisterClient struct {
	grpc.ClientStream
}

func (x *chaincodeSupportRegisterClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChaincodeSupport service

type ChaincodeSupportServer interface {
	Register(ChaincodeSupport_RegisterServer) error
}

func RegisterChaincodeSupportServer(s *grpc.Server, srv ChaincodeSupportServer) {
	s.RegisterService(&_ChaincodeSupport_serviceDesc, srv)
}

func _ChaincodeSupport_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeSupportServer).Register(&chaincodeSupportRegisterServer{stream})
}

type ChaincodeSupport_RegisterServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeSupportRegisterServer struct {
	grpc.ServerStream
}

func (x *chaincodeSupportRegisterServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeSupportRegisterServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChaincodeSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChaincodeSupport",
	HandlerType: (*ChaincodeSupportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ChaincodeSupport_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("blockchainmessages.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x8e, 0x2e, 0x96, 0xad, 0x23, 0x59, 0x66, 0xc6, 0x8e, 0x2d, 0xf8, 0xbf, 0x24, 0x3f, 0xff,
	0x34, 0x30, 0x82, 0x42, 0x49, 0x95, 0xb4, 0x28, 0x90, 0x20, 0x28, 0x2d, 0x32, 0x0e, 0x63, 0x89,
	0x52, 0x46, 0xb2, 0x11, 0xaf, 0x0c, 0x5a, 0x1a, 0xcb, 0x44, 0x64, 0x52, 0x20, 0x29, 0x43, 0xee,
	0x2a, 0xeb, 0xae, 0xfa, 0x0c, 0x7d, 0x84, 0x2e, 0xba, 0xe8, 0xae, 0x9b, 0x3e, 0x4a, 0x9f, 0xa3,
	0x67, 0x86, 0x17, 0x91, 0x92, 0x6c, 0xb8, 0xe8, 0xa6, 0x2b, 0xf1, 0x5c, 0xe7, 0x5c, 0xbe, 0x73,
	0x66, 0x04, 0xd5, 0xb3, 0x91, 0xd3, 0xff, 0xd4, 0xbf, 0x30, 0x2d, 0xfb, 0x92, 0x79, 0x9e, 0x39,
	0x64, 0x5e, 0x6d, 0xec, 0x3a, 0xbe, 0x43, 0x0a, 0xe2, 0xc7, 0xdb, 0xdd, 0x12, 0xc2, 0xbe, 0x33,
	0x60, 0xec, 0x8a, 0xd9, 0x7e, 0x20, 0xdd, 0x7d, 0x38, 0x74, 0x9c, 0xe1, 0x88, 0x3d, 0x13, 0xd4,
	0xd9, 0xe4, 0xfc, 0x99, 0x6f, 0xa1, 0xbd, 0x6f, 0x5e, 0x8e, 0x03, 0x05, 0xf9, 0x6b, 0x28, 0x35,
	0x22, 0x43, 0x5d, 0x25, 0x04, 0xf2, 0x63, 0xd3, 0xbf, 0xa8, 0x66, 0x1e, 0x65, 0xf6, 0x8a, 0x54,
	0x7c, 0x73, 0x9e, 0x6d, 0x5e, 0xb2, 0x6a, 0x36, 0xe0, 0xf1, 0x6f, 0xf9, 0x31, 0x54, 0x66, 0x66,
	0xf6, 0x78, 0xe2, 0x73, 0x2d, 0xd3, 0x1d, 0x7a, 0x68, 0x99, 0xdb, 0x2b, 0x53, 0xf1, 0x2d, 0xff,
	0x9c, 0x03, 0xe8, 0x4d, 0xbb, 0xcc, 0x0f, 0x54, 0x9e, 0x42, 0xde, 0xbf, 0x1e, 0x33, 0xe1, 0xbc,
	0x52, 0xdf, 0x0e, 0x22, 0xf0, 0x6a, 0x42, 0xa3, 0x3b, 0x66, 0xfd, 0x5a, 0x0f, 0xa5, 0x54, 0xe8,
	0x10, 0x19, 0xca, 0x03, 0x76, 0x6e, 0x4e, 0x46, 0x68, 0x3b, 0x60, 0x53, 0x71, 0x78, 0x9e, 0xa6,
	0x78, 0x64, 0x0b, 0x56, 0x3c, 0xf4, 0xad, 0x56, 0x73, 0x22, 0xb2, 0x80, 0x20, 0xaf, 0x60, 0xd5,
	0x9f, 0x72, 0x77, 0x5e, 0x35, 0x8f, 0xb1, 0x94, 0xea, 0xff, 0x4b, 0x1d, 0x24, 0x42, 0xa9, 0x75,
	0xad, 0xcb, 0xf1, 0xc8, 0x3a, 0xb7, 0xd8, 0x80, 0x6b, 0xd2, 0xc8, 0x62, 0xf7, 0x73, 0x16, 0x2a,
	0x69, 0x19, 0x79, 0x06, 0x05, 0xb3, 0xef, 0x5b, 0x8e, 0x1d, 0xc6, 0xbd, 0x13, 0xb9, 0x8b, 0x0b,
	0xa0, 0x08, 0x31, 0x0d, 0xd5, 0x48, 0x0d, 0xf2, 0x23, 0xd3, 0x1e, 0x8a, 0x90, 0x2b, 0xf5, 0xdd,
	0x05, 0xf5, 0x44, 0xaa, 0x5c, 0x8f, 0x60, 0x0b, 0xfa, 0xb3, 0x16, 0x88, 0x64, 0x4a, 0xf5, 0xcd,
	0x05, 0x33, 0x5d, 0xa5, 0x49, 0x3d, 0xf2, 0x12, 0x8a, 0x16, 0xcf, 0x45, 0xe1, 0x55, 0xcf, 0x0b,
	0xa3, 0xed, 0x45, 0x23, 0xae, 0x41, 0x67, 0x8a, 0xe4, 0x11, 0x1e, 0x36, 0xf1, 0x7c, 0xe7, 0x52,
	0x57, 0x0f, 0x98, 0x5d, 0x5d, 0x11, 0x95, 0x4b, 0xb2, 0xe4, 0x5f, 0x72, 0xb0, 0x9e, 0x8a, 0x95,
	0x27, 0x94, 0xe8, 0xdb, 0xad, 0x09, 0x89, 0xde, 0xcd, 0x25, 0x94, 0xbd, 0x63, 0x42, 0xcf, 0x61,
	0xb5, 0xef, 0x3b, 0x6e, 0xcb, 0x1b, 0x86, 0x35, 0xb8, 0x29, 0x9d, 0x48, 0x8d, 0x54, 0xb1, 0xd5,
	0x88, 0x67, 0x67, 0xe2, 0x8b, 0x02, 0xac, 0xd0, 0x88, 0x24, 0x8f, 0x61, 0xdd, 0x63, 0xfd, 0x89,
	0xcb, 0x1a, 0x8e, 0xed, 0xb3, 0xa9, 0x1f, 0x26, 0x9a, 0x66, 0x92, 0x0e, 0x6c, 0xf5, 0x1d, 0xfb,
	0xdc, 0x1a, 0xe0, 0xc0, 0x58, 0xe6, 0xc8, 0xf2, 0xaf, 0x9b, 0x38, 0x3c, 0xa3, 0x6a, 0x41, 0x24,
	0xfa, 0xef, 0xf8, 0xf8, 0x25, 0x3a, 0x74, 0xa9, 0x25, 0xd9, 0x85, 0xb5, 0x4b, 0xe6, 0x9b, 0x03,
	0xd3, 0x37, 0xab, 0xab, 0xe8, 0xa5, 0x4c, 0x63, 0x9a, 0xfc, 0x17, 0xc0, 0xf4, 0x7d, 0xd7, 0x3a,
	0x9b, 0xf8, 0xcc, 0xab, 0xae, 0x21, 0x36, 0x8b, 0x34, 0xc1, 0x91, 0xdf, 0x40, 0x9e, 0x17, 0x91,
	0xac, 0x43, 0xf1, 0xc8, 0x50, 0xb5, 0xb7, 0xba, 0xa1, 0xa9, 0xd2, 0x3d, 0x02, 0x50, 0x38, 0x68,
	0x37, 0x15, 0xe3, 0x40, 0xca, 0x90, 0x35, 0xc8, 0x1b, 0x6d, 0x55, 0x93, 0xb2, 0x64, 0x15, 0x72,
	0x0d, 0x85, 0x4a, 0x39, 0xce, 0x7a, 0xaf, 0x1c, 0x2b, 0x52, 0x5e, 0xfe, 0x2d, 0x03, 0x85, 0x9e,
	0xc0, 0x31, 0x79, 0x01, 0x6b, 0x51, 0x63, 0x44, 0xd7, 0x4a, 0xf5, 0x07, 0x4b, 0xbb, 0xf6, 0xee,
	0x1e, 0x8d, 0x15, 0x89, 0x0e, 0x15, 0xcb, 0xbe, 0x72, 0xfa, 0x26, 0x47, 0xb1, 0x30, 0x0d, 0x3a,
	0xf7, 0x70, 0x49, 0x1b, 0x92, 0x6a, 0xe8, 0x64, 0xce, 0x30, 0x31, 0x33, 0xb9, 0x3b, 0xcd, 0xcc,
	0x7e, 0x01, 0xf2, 0xdc, 0x50, 0xfe, 0x3d, 0x0b, 0xc5, 0x78, 0x1f, 0xfc, 0xa5, 0x85, 0x51, 0x9d,
	0x8d, 0x7d, 0x56, 0xac, 0xa0, 0x88, 0xe4, 0x75, 0x8f, 0xd7, 0xc6, 0x54, 0x04, 0x94, 0xa7, 0x09,
	0x0e, 0xef, 0x19, 0x82, 0xa1, 0x2b, 0x36, 0x49, 0x5e, 0xc0, 0x24, 0xa6, 0xff, 0x89, 0x38, 0x92,
	0xff, 0x1f, 0xe2, 0xa4, 0x0c, 0x6b, 0x0d, 0xaa, 0x29, 0x3d, 0xbd, 0x6d, 0x20, 0x4c, 0x10, 0x35,
	0xda, 0xc7, 0x9e, 0x66, 0x74, 0x39, 0x99, 0x91, 0x5f, 0x03, 0xb4, 0x26, 0xbe, 0x69, 0x07, 0x85,
	0x0c, 0x8a, 0x23, 0x32, 0x0c, 0x36, 0x7b, 0x44, 0xf2, 0x1d, 0x6a, 0x25, 0x16, 0x6c, 0x40, 0xc8,
	0xbf, 0x66, 0x61, 0x27, 0x6e, 0x95, 0xca, 0xc6, 0x23, 0xe7, 0xfa, 0x92, 0x85, 0xbe, 0x5e, 0xc1,
	0x7a, 0x3f, 0x89, 0xa1, 0x5b, 0x01, 0x46, 0xd3, 0xba, 0xe4, 0x3b, 0x58, 0x67, 0xe7, 0xe7, 0x0c,
	0x9b, 0x7e, 0xc5, 0x54, 0xd3, 0x67, 0x21, 0xc4, 0x76, 0x6b, 0xc1, 0x3d, 0x55, 0x8b, 0xee, 0xa9,
	0x5a, 0x2f, 0xba, 0xa7, 0x68, 0xda, 0x40, 0x2c, 0x30, 0xf4, 0xd6, 0x31, 0xfb, 0x9f, 0xf0, 0x16,
	0x14, 0xed, 0x2c, 0xd3, 0x24, 0x8b, 0x18, 0xb0, 0xca, 0xa6, 0xac, 0xaf, 0xd9, 0x57, 0xa2, 0x9d,
	0x95, 0xfa, 0xcb, 0x85, 0xd0, 0xd2, 0x29, 0xd5, 0x34, 0x54, 0x9f, 0x70, 0x1c, 0xa2, 0x8d, 0xe5,
	0x3a, 0x36, 0x17, 0xd0, 0xc8, 0x89, 0x5c, 0x83, 0xad, 0x65, 0x0a, 0x7c, 0x30, 0xd5, 0x76, 0xe3,
	0x50, 0xa3, 0xc1, 0x90, 0x76, 0x4f, 0xba, 0x3d, 0xad, 0x85, 0xa5, 0xff, 0x9c, 0x49, 0x14, 0x2f,
	0x3d, 0x2a, 0x7f, 0xaf, 0x78, 0x7b, 0xb0, 0x61, 0x0d, 0x70, 0x45, 0x33, 0x57, 0x38, 0x54, 0x46,
	0xc3, 0xf0, 0x4e, 0x9e, 0x67, 0xcb, 0x3f, 0x66, 0xa1, 0x3a, 0x73, 0xc5, 0xb1, 0x8a, 0xc8, 0x8a,
	0xd0, 0x8a, 0xf3, 0xd0, 0x37, 0x47, 0x23, 0xe6, 0x36, 0x98, 0xeb, 0x8b, 0x00, 0xca, 0x34, 0xc1,
	0x99, 0xc9, 0xbb, 0xd6, 0xd0, 0x16, 0x27, 0xc4, 0x72, 0xce, 0xe1, 0x60, 0x1a, 0x9b, 0xd7, 0x23,
	0xc7, 0x1c, 0x84, 0xd5, 0x8f, 0x48, 0x2e, 0x39, 0x43, 0x00, 0x59, 0x78, 0xf9, 0xe5, 0x03, 0x49,
	0x48, 0xa6, 0xf0, 0xbc, 0x32, 0xb7, 0x17, 0x9f, 0x40, 0x65, 0x6c, 0xba, 0x58, 0xd1, 0x56, 0xa4,
	0x51, 0x10, 0x1a, 0x73, 0x5c, 0xf2, 0x1a, 0x4a, 0xfe, 0x34, 0xc6, 0x85, 0x18, 0x8b, 0xdb, 0x91,
	0x93, 0x54, 0x97, 0x7f, 0x5a, 0x01, 0x29, 0x2e, 0x49, 0x2b, 0x78, 0x43, 0x91, 0xaf, 0x52, 0x0b,
	0xe6, 0x3f, 0x0b, 0x5d, 0x08, 0xf5, 0x92, 0x7b, 0xe6, 0x5b, 0x28, 0xc6, 0x6f, 0xa8, 0x3b, 0xa0,
	0x77, 0xa6, 0x7c, 0x4b, 0xdd, 0xf0, 0xed, 0xe4, 0x4f, 0xad, 0x41, 0xb8, 0x7d, 0xc4, 0x37, 0x79,
	0x0f, 0x1b, 0x5e, 0xba, 0x71, 0xa2, 0x70, 0xa5, 0xfa, 0xa3, 0x45, 0xac, 0xa4, 0xf5, 0xe8, 0xbc,
	0x21, 0x79, 0x03, 0x95, 0x18, 0x49, 0x1a, 0x7f, 0x1d, 0x8a, 0x0a, 0x2f, 0xbb, 0x60, 0x85, 0x94,
	0xce, 0x69, 0xcb, 0x7f, 0x64, 0x97, 0x5f, 0x4d, 0xb8, 0x81, 0xa8, 0x76, 0xa0, 0x23, 0xee, 0x29,
	0x5e, 0x4e, 0x15, 0x80, 0x88, 0x42, 0x69, 0x96, 0xdf, 0x4c, 0xba, 0xa1, 0xf7, 0xf0, 0x8e, 0x2a,
	0xc2, 0x0a, 0x2e, 0x2a, 0xf5, 0x44, 0xca, 0x93, 0x0d, 0x28, 0xf5, 0xa8, 0x62, 0x74, 0x95, 0x86,
	0xd8, 0x5b, 0x2b, 0xdc, 0x65, 0xa3, 0xdd, 0xea, 0x34, 0xb5, 0x1e, 0x1a, 0x15, 0xb8, 0xaa, 0x46,
	0x69, 0x9b, 0x4a, 0xab, 0x5c, 0x72, 0xa0, 0xf5, 0x4e, 0xbb, 0x3d, 0xa5, 0xa7, 0x49, 0x6b, 0x9c,
	0xec, 0x1c, 0x45, 0x64, 0x91, 0x93, 0xaa, 0xd6, 0x0c, 0x49, 0xc0, 0x3d, 0x26, 0xe9, 0xc6, 0x71,
	0xfb, 0x50, 0x3b, 0x6d, 0xbc, 0x53, 0x74, 0xa3, 0xc1, 0x6f, 0xc9, 0x12, 0x91, 0xa0, 0x1c, 0x72,
	0x3f, 0x1c, 0x69, 0xf4, 0x44, 0x2a, 0x07, 0x21, 0x77, 0x3b, 0x6d, 0xa3, 0xab, 0x49, 0xeb, 0xfc,
	0xb4, 0x40, 0x50, 0x21, 0x9b, 0xb0, 0x21, 0x3e, 0x4f, 0x67, 0xd1, 0x6c, 0xf0, 0x68, 0x03, 0x66,
	0x10, 0x93, 0x44, 0x1e, 0xc0, 0x7d, 0x8c, 0xfe, 0x20, 0xf4, 0x17, 0x9e, 0x7e, 0x1f, 0xe1, 0xbd,
	0xbd, 0xc0, 0x3e, 0x35, 0x70, 0x1f, 0x4b, 0x84, 0xfc, 0x0b, 0x76, 0x16, 0x65, 0x8d, 0x66, 0x1b,
	0x03, 0xd8, 0xe4, 0x59, 0x1c, 0x6a, 0x5a, 0x47, 0x69, 0xea, 0xc7, 0x9a, 0xb4, 0x25, 0x7f, 0x03,
	0xe5, 0xce, 0xc4, 0xef, 0xfa, 0xb8, 0xe8, 0x74, 0xfb, 0xdc, 0xc1, 0xf8, 0x73, 0x9f, 0xd8, 0x75,
	0xb8, 0xb3, 0xf9, 0x27, 0xdf, 0xd7, 0x57, 0xe6, 0x68, 0xc2, 0xc2, 0xb9, 0x0c, 0x08, 0x59, 0x83,
	0x0d, 0x8a, 0x4f, 0x49, 0xf6, 0x61, 0xc2, 0xdc, 0x6b, 0x61, 0xce, 0x27, 0x0e, 0x61, 0xe7, 0xfa,
	0x87, 0xb1, 0x7d, 0x4c, 0x93, 0x6d, 0x28, 0x30, 0x7b, 0xc0, 0x25, 0xc1, 0xfe, 0x08, 0x29, 0xf9,
	0x0b, 0xd8, 0x9c, 0x73, 0x63, 0x70, 0xf8, 0x54, 0x20, 0x1b, 0x5f, 0x1c, 0x59, 0x4b, 0x95, 0x9f,
	0xc0, 0xd6, 0x9c, 0x5a, 0x63, 0xe4, 0x78, 0x6c, 0x41, 0x4f, 0xc1, 0xcc, 0xd3, 0x7a, 0x78, 0xc8,
	0x31, 0x0f, 0xf8, 0xce, 0x89, 0xfd, 0x90, 0x59, 0xf0, 0x41, 0x99, 0x37, 0x76, 0x6c, 0x3c, 0x4e,
	0x83, 0x75, 0x34, 0xf4, 0x14, 0x7b, 0x20, 0x7c, 0x06, 0x7f, 0x3d, 0x12, 0xcf, 0x95, 0x1b, 0xce,
	0xa6, 0x69, 0x2b, 0x3e, 0x96, 0x17, 0xa6, 0xd7, 0x72, 0xdc, 0xe0, 0xe8, 0x35, 0x1a, 0x91, 0x61,
	0x3e, 0xb9, 0x28, 0x9f, 0xa7, 0x2f, 0x61, 0x6b, 0xd9, 0x15, 0xce, 0x97, 0x7f, 0xe7, 0x68, 0xbf,
	0xa9, 0x37, 0x70, 0x24, 0x10, 0x71, 0x8d, 0xb6, 0xf1, 0x56, 0x57, 0x35, 0xa3, 0xa7, 0x2b, 0x4d,
	0x29, 0xf3, 0xf4, 0x7b, 0xd8, 0x98, 0x7b, 0xf5, 0xcc, 0x8f, 0x11, 0x62, 0x37, 0x06, 0xed, 0xa9,
	0xaa, 0x75, 0x9a, 0xed, 0x13, 0x1c, 0xa7, 0x14, 0x37, 0x40, 0x31, 0x0e, 0x15, 0xc2, 0x74, 0xc6,
	0x0d, 0xb0, 0x9b, 0x23, 0x3b, 0xb0, 0x39, 0x63, 0xe2, 0xf8, 0xb5, 0x74, 0x83, 0xe3, 0x32, 0x5f,
	0xff, 0x98, 0xd8, 0x79, 0xdd, 0xc9, 0x78, 0xec, 0xe0, 0x7a, 0x57, 0x71, 0x02, 0xd8, 0xd0, 0xf2,
	0x7c, 0xe6, 0x92, 0xea, 0x4d, 0x1b, 0x6f, 0xf7, 0x46, 0x89, 0x7c, 0x6f, 0x2f, 0xf3, 0x3c, 0xb3,
	0xff, 0x25, 0x6c, 0x3b, 0xee, 0xb0, 0x76, 0x81, 0x5b, 0xc1, 0x1d, 0xb1, 0xc1, 0x90, 0xb9, 0xa1,
	0xc1, 0x3e, 0xd9, 0x8f, 0xff, 0xaa, 0x86, 0x26, 0xde, 0x59, 0xf0, 0x27, 0xf5, 0xc5, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x12, 0x6f, 0x49, 0x01, 0xc7, 0x0e, 0x00, 0x00,
}
