// Code generated by protoc-gen-go.
// source: devops.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BuildResult_StatusCode int32

const (
	BuildResult_UNDEFINED BuildResult_StatusCode = 0
	BuildResult_SUCCESS   BuildResult_StatusCode = 1
	BuildResult_FAILURE   BuildResult_StatusCode = 2
)

var BuildResult_StatusCode_name = map[int32]string{
	0: "UNDEFINED",
	1: "SUCCESS",
	2: "FAILURE",
}
var BuildResult_StatusCode_value = map[string]int32{
	"UNDEFINED": 0,
	"SUCCESS":   1,
	"FAILURE":   2,
}

func (x BuildResult_StatusCode) String() string {
	return proto.EnumName(BuildResult_StatusCode_name, int32(x))
}
func (BuildResult_StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{4, 0} }

// Secret is a temporary object to establish security with the Devops.
// A better solution using certificate will be introduced later
type Secret struct {
	EnrollId     string `protobuf:"bytes,1,opt,name=enrollId" json:"enrollId,omitempty"`
	EnrollSecret string `protobuf:"bytes,2,opt,name=enrollSecret" json:"enrollSecret,omitempty"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type SigmaInput struct {
	Secret   *Secret `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	AppTCert []byte  `protobuf:"bytes,2,opt,name=appTCert,proto3" json:"appTCert,omitempty"`
	Data     []byte  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SigmaInput) Reset()                    { *m = SigmaInput{} }
func (m *SigmaInput) String() string            { return proto.CompactTextString(m) }
func (*SigmaInput) ProtoMessage()               {}
func (*SigmaInput) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *SigmaInput) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

type ExecuteWithBinding struct {
	ChaincodeInvocationSpec *ChaincodeInvocationSpec `protobuf:"bytes,1,opt,name=chaincodeInvocationSpec" json:"chaincodeInvocationSpec,omitempty"`
	Binding                 []byte                   `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
}

func (m *ExecuteWithBinding) Reset()                    { *m = ExecuteWithBinding{} }
func (m *ExecuteWithBinding) String() string            { return proto.CompactTextString(m) }
func (*ExecuteWithBinding) ProtoMessage()               {}
func (*ExecuteWithBinding) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ExecuteWithBinding) GetChaincodeInvocationSpec() *ChaincodeInvocationSpec {
	if m != nil {
		return m.ChaincodeInvocationSpec
	}
	return nil
}

type SigmaOutput struct {
	Tcert        []byte `protobuf:"bytes,1,opt,name=tcert,proto3" json:"tcert,omitempty"`
	Sigma        []byte `protobuf:"bytes,2,opt,name=sigma,proto3" json:"sigma,omitempty"`
	Asn1Encoding []byte `protobuf:"bytes,3,opt,name=asn1Encoding,proto3" json:"asn1Encoding,omitempty"`
}

func (m *SigmaOutput) Reset()                    { *m = SigmaOutput{} }
func (m *SigmaOutput) String() string            { return proto.CompactTextString(m) }
func (*SigmaOutput) ProtoMessage()               {}
func (*SigmaOutput) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type BuildResult struct {
	Status         BuildResult_StatusCode   `protobuf:"varint,1,opt,name=status,enum=protos.BuildResult_StatusCode" json:"status,omitempty"`
	Msg            string                   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	DeploymentSpec *ChaincodeDeploymentSpec `protobuf:"bytes,3,opt,name=deploymentSpec" json:"deploymentSpec,omitempty"`
}

func (m *BuildResult) Reset()                    { *m = BuildResult{} }
func (m *BuildResult) String() string            { return proto.CompactTextString(m) }
func (*BuildResult) ProtoMessage()               {}
func (*BuildResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *BuildResult) GetDeploymentSpec() *ChaincodeDeploymentSpec {
	if m != nil {
		return m.DeploymentSpec
	}
	return nil
}

type TransactionRequest struct {
	TransactionUuid string `protobuf:"bytes,1,opt,name=transactionUuid" json:"transactionUuid,omitempty"`
}

func (m *TransactionRequest) Reset()                    { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()               {}
func (*TransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func init() {
	proto.RegisterType((*Secret)(nil), "protos.Secret")
	proto.RegisterType((*SigmaInput)(nil), "protos.SigmaInput")
	proto.RegisterType((*ExecuteWithBinding)(nil), "protos.ExecuteWithBinding")
	proto.RegisterType((*SigmaOutput)(nil), "protos.SigmaOutput")
	proto.RegisterType((*BuildResult)(nil), "protos.BuildResult")
	proto.RegisterType((*TransactionRequest)(nil), "protos.TransactionRequest")
	proto.RegisterEnum("protos.BuildResult_StatusCode", BuildResult_StatusCode_name, BuildResult_StatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Devops service

type DevopsClient interface {
	// Log in - passed Secret object and returns Response object, where
	// msg is the security context to be used in subsequent invocations
	Login(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error)
	// Build the chaincode package.
	// Response vs. ChaincodeDeploymentSpec see the comments at for Deploy
	Build(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*Response, error)
	// Deploy the chaincode package to the chain.
	// Before the call was returning a ChaincodeDeploymentSpec
	// Now it is inglobated into the response message to uniform the call
	Deploy(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*Response, error)
	// Invoke chaincode.
	Invoke(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error)
	// Query chaincode.
	Query(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error)
	// IssueTxSet deploys a transactions set or an extension of it in case the set that it refers to was already defined
	// The response returned contains another response chained into it.
	// The outmost response is related to the TxSet and contains the TxID assigned to the set
	// The inner response contains the result of the execution of the dafault transaction of the issued set.
	IssueTxSet(ctx context.Context, in *TxSetSpec, opts ...grpc.CallOption) (*Response, error)
	// IssueExtensionSet deploys an extension to an existing TxSet. Note that the active transaction of the
	// set is not changed by issuing a set extension.
	IssueSetExtension(ctx context.Context, in *TxSetSpec, opts ...grpc.CallOption) (*Response, error)
	// Modifies the active transaction of a transactions set.
	// Contains two responses. The inner one contains the response for the execution of the new default transaction.
	// The outer one contains a positive response if the history change did not cause conflicts in the chain.
	Mutate(ctx context.Context, in *MutantSpec, opts ...grpc.CallOption) (*Response, error)
	// Queries the state of a given Tx Set
	QueryTxSetState(ctx context.Context, in *MutantSpec, opts ...grpc.CallOption) (*Response, error)
	// Retrieve a TCert.
	EXP_GetApplicationTCert(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error)
	// Prepare for performing a TX, which will return a binding that can later be used to sign and then execute a transaction.
	EXP_PrepareForTx(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error)
	// Prepare for performing a TX, which will return a binding that can later be used to sign and then execute a transaction.
	EXP_ProduceSigma(ctx context.Context, in *SigmaInput, opts ...grpc.CallOption) (*Response, error)
	// Execute a transaction with a specific binding
	EXP_ExecuteWithBinding(ctx context.Context, in *ExecuteWithBinding, opts ...grpc.CallOption) (*Response, error)
}

type devopsClient struct {
	cc *grpc.ClientConn
}

func NewDevopsClient(cc *grpc.ClientConn) DevopsClient {
	return &devopsClient{cc}
}

func (c *devopsClient) Login(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Build(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Build", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Deploy(ctx context.Context, in *ChaincodeSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Invoke(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Query(ctx context.Context, in *ChaincodeInvocationSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) IssueTxSet(ctx context.Context, in *TxSetSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/IssueTxSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) IssueSetExtension(ctx context.Context, in *TxSetSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/IssueSetExtension", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) Mutate(ctx context.Context, in *MutantSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/Mutate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) QueryTxSetState(ctx context.Context, in *MutantSpec, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/QueryTxSetState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) EXP_GetApplicationTCert(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/EXP_GetApplicationTCert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) EXP_PrepareForTx(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/EXP_PrepareForTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) EXP_ProduceSigma(ctx context.Context, in *SigmaInput, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/EXP_ProduceSigma", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devopsClient) EXP_ExecuteWithBinding(ctx context.Context, in *ExecuteWithBinding, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Devops/EXP_ExecuteWithBinding", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Devops service

type DevopsServer interface {
	// Log in - passed Secret object and returns Response object, where
	// msg is the security context to be used in subsequent invocations
	Login(context.Context, *Secret) (*Response, error)
	// Build the chaincode package.
	// Response vs. ChaincodeDeploymentSpec see the comments at for Deploy
	Build(context.Context, *ChaincodeSpec) (*Response, error)
	// Deploy the chaincode package to the chain.
	// Before the call was returning a ChaincodeDeploymentSpec
	// Now it is inglobated into the response message to uniform the call
	Deploy(context.Context, *ChaincodeSpec) (*Response, error)
	// Invoke chaincode.
	Invoke(context.Context, *ChaincodeInvocationSpec) (*Response, error)
	// Query chaincode.
	Query(context.Context, *ChaincodeInvocationSpec) (*Response, error)
	// IssueTxSet deploys a transactions set or an extension of it in case the set that it refers to was already defined
	// The response returned contains another response chained into it.
	// The outmost response is related to the TxSet and contains the TxID assigned to the set
	// The inner response contains the result of the execution of the dafault transaction of the issued set.
	IssueTxSet(context.Context, *TxSetSpec) (*Response, error)
	// IssueExtensionSet deploys an extension to an existing TxSet. Note that the active transaction of the
	// set is not changed by issuing a set extension.
	IssueSetExtension(context.Context, *TxSetSpec) (*Response, error)
	// Modifies the active transaction of a transactions set.
	// Contains two responses. The inner one contains the response for the execution of the new default transaction.
	// The outer one contains a positive response if the history change did not cause conflicts in the chain.
	Mutate(context.Context, *MutantSpec) (*Response, error)
	// Queries the state of a given Tx Set
	QueryTxSetState(context.Context, *MutantSpec) (*Response, error)
	// Retrieve a TCert.
	EXP_GetApplicationTCert(context.Context, *Secret) (*Response, error)
	// Prepare for performing a TX, which will return a binding that can later be used to sign and then execute a transaction.
	EXP_PrepareForTx(context.Context, *Secret) (*Response, error)
	// Prepare for performing a TX, which will return a binding that can later be used to sign and then execute a transaction.
	EXP_ProduceSigma(context.Context, *SigmaInput) (*Response, error)
	// Execute a transaction with a specific binding
	EXP_ExecuteWithBinding(context.Context, *ExecuteWithBinding) (*Response, error)
}

func RegisterDevopsServer(s *grpc.Server, srv DevopsServer) {
	s.RegisterService(&_Devops_serviceDesc, srv)
}

func _Devops_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Login(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Build(ctx, req.(*ChaincodeSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Deploy(ctx, req.(*ChaincodeSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeInvocationSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Invoke(ctx, req.(*ChaincodeInvocationSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeInvocationSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Query(ctx, req.(*ChaincodeInvocationSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_IssueTxSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxSetSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).IssueTxSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/IssueTxSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).IssueTxSet(ctx, req.(*TxSetSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_IssueSetExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxSetSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).IssueSetExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/IssueSetExtension",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).IssueSetExtension(ctx, req.(*TxSetSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutantSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).Mutate(ctx, req.(*MutantSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_QueryTxSetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutantSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).QueryTxSetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/QueryTxSetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).QueryTxSetState(ctx, req.(*MutantSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_EXP_GetApplicationTCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).EXP_GetApplicationTCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/EXP_GetApplicationTCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).EXP_GetApplicationTCert(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_EXP_PrepareForTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).EXP_PrepareForTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/EXP_PrepareForTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).EXP_PrepareForTx(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_EXP_ProduceSigma_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigmaInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).EXP_ProduceSigma(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/EXP_ProduceSigma",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).EXP_ProduceSigma(ctx, req.(*SigmaInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devops_EXP_ExecuteWithBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteWithBinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevopsServer).EXP_ExecuteWithBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Devops/EXP_ExecuteWithBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevopsServer).EXP_ExecuteWithBinding(ctx, req.(*ExecuteWithBinding))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devops_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Devops",
	HandlerType: (*DevopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Devops_Login_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Devops_Build_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _Devops_Deploy_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _Devops_Invoke_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Devops_Query_Handler,
		},
		{
			MethodName: "IssueTxSet",
			Handler:    _Devops_IssueTxSet_Handler,
		},
		{
			MethodName: "IssueSetExtension",
			Handler:    _Devops_IssueSetExtension_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _Devops_Mutate_Handler,
		},
		{
			MethodName: "QueryTxSetState",
			Handler:    _Devops_QueryTxSetState_Handler,
		},
		{
			MethodName: "EXP_GetApplicationTCert",
			Handler:    _Devops_EXP_GetApplicationTCert_Handler,
		},
		{
			MethodName: "EXP_PrepareForTx",
			Handler:    _Devops_EXP_PrepareForTx_Handler,
		},
		{
			MethodName: "EXP_ProduceSigma",
			Handler:    _Devops_EXP_ProduceSigma_Handler,
		},
		{
			MethodName: "EXP_ExecuteWithBinding",
			Handler:    _Devops_EXP_ExecuteWithBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor3,
}

func init() { proto.RegisterFile("devops.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x4e, 0x13, 0x41,
	0x14, 0xa5, 0x60, 0x8b, 0xdc, 0x56, 0x28, 0x13, 0x95, 0xa6, 0x0f, 0x6a, 0xf6, 0xc1, 0x90, 0x98,
	0x10, 0x2d, 0x91, 0x44, 0x22, 0x26, 0xd0, 0x2e, 0xd0, 0x04, 0x11, 0x77, 0xdb, 0xa8, 0x0f, 0xc6,
	0x4c, 0x77, 0xaf, 0x65, 0xc3, 0x76, 0x66, 0xdd, 0x99, 0x21, 0xe5, 0x13, 0xfc, 0x42, 0xff, 0xc4,
	0x67, 0x77, 0x66, 0x76, 0x41, 0xa0, 0x8d, 0xc5, 0xa7, 0x9d, 0x73, 0xe7, 0x9c, 0x39, 0x7b, 0xee,
	0xde, 0x1d, 0xa8, 0x85, 0x78, 0xce, 0x13, 0xb1, 0x91, 0xa4, 0x5c, 0x72, 0x52, 0x31, 0x0f, 0xd1,
	0x6c, 0x0c, 0x62, 0x1e, 0x9c, 0x05, 0xa7, 0x34, 0x62, 0x23, 0x14, 0x82, 0x0e, 0x31, 0x67, 0x34,
	0x6b, 0xdf, 0xe9, 0x20, 0x8d, 0x02, 0x8b, 0x9c, 0x43, 0xa8, 0xf8, 0x18, 0xa4, 0x28, 0x49, 0x13,
	0xee, 0x23, 0x4b, 0x79, 0x1c, 0x77, 0xc3, 0x46, 0xe9, 0x59, 0x69, 0x7d, 0xc9, 0xbb, 0xc4, 0xc4,
	0x81, 0x9a, 0x5d, 0x5b, 0x6e, 0x63, 0xde, 0xec, 0x5f, 0xab, 0x39, 0x21, 0x80, 0x1f, 0x0d, 0x47,
	0xb4, 0xcb, 0x12, 0x25, 0xc9, 0x73, 0xa8, 0x08, 0xcb, 0xd5, 0x67, 0x55, 0x5b, 0xcb, 0xd6, 0x4f,
	0x6c, 0x58, 0xb6, 0x97, 0xef, 0x6a, 0x57, 0x9a, 0x24, 0xbd, 0x36, 0xa6, 0xf6, 0xd4, 0x9a, 0x77,
	0x89, 0x09, 0x81, 0x7b, 0x21, 0x95, 0xb4, 0xb1, 0x60, 0xea, 0x66, 0xed, 0xfc, 0x2c, 0x01, 0x71,
	0xc7, 0x18, 0x28, 0x89, 0x9f, 0x22, 0x79, 0xba, 0x17, 0xb1, 0x30, 0x62, 0x43, 0xf2, 0x05, 0xd6,
	0x4c, 0xd6, 0x80, 0x87, 0xd8, 0x65, 0xe7, 0x3c, 0xa0, 0x32, 0xe2, 0xcc, 0x4f, 0x30, 0xc8, 0xfd,
	0x9f, 0x16, 0xfe, 0xed, 0xc9, 0x34, 0x6f, 0x9a, 0x9e, 0x34, 0x60, 0x71, 0x60, 0x5d, 0xf2, 0x17,
	0x2c, 0xa0, 0xf3, 0x15, 0xaa, 0x26, 0xf1, 0x07, 0x25, 0x75, 0xe4, 0x87, 0x50, 0x96, 0x81, 0xce,
	0x51, 0x32, 0x34, 0x0b, 0x74, 0x55, 0x68, 0x52, 0x2e, 0xb6, 0x40, 0x37, 0x94, 0x0a, 0xf6, 0xca,
	0xd5, 0x86, 0xfa, 0x64, 0x1b, 0xf1, 0x5a, 0xcd, 0xf9, 0x55, 0x82, 0xea, 0x9e, 0x8a, 0xe2, 0xd0,
	0x43, 0xa1, 0x62, 0x49, 0xb6, 0xb2, 0x96, 0x4a, 0x2a, 0x95, 0x30, 0x06, 0xcb, 0xad, 0x27, 0x45,
	0xa4, 0xbf, 0x48, 0x1b, 0xbe, 0x61, 0xb4, 0xb3, 0x18, 0x5e, 0xce, 0x26, 0x75, 0x58, 0x18, 0x89,
	0x61, 0xfe, 0xcd, 0xf4, 0x92, 0x1c, 0xc0, 0x72, 0x88, 0x49, 0xcc, 0x2f, 0x46, 0xc8, 0xa4, 0x69,
	0xd2, 0xc2, 0x94, 0x26, 0x75, 0xae, 0xd1, 0xbc, 0x1b, 0x32, 0xe7, 0x75, 0xf6, 0xcd, 0x2f, 0x0d,
	0xc9, 0x03, 0x58, 0xea, 0x1f, 0x77, 0xdc, 0xfd, 0xee, 0xb1, 0xdb, 0xa9, 0xcf, 0x91, 0x2a, 0x2c,
	0xfa, 0xfd, 0x76, 0xdb, 0xf5, 0xfd, 0x7a, 0x49, 0x83, 0xfd, 0xdd, 0xee, 0x51, 0xdf, 0x73, 0xeb,
	0xf3, 0xce, 0x3b, 0x20, 0xbd, 0x94, 0x32, 0x41, 0x03, 0xdd, 0x65, 0x0f, 0x7f, 0x28, 0x14, 0x92,
	0xac, 0xc3, 0x8a, 0xbc, 0xaa, 0xf6, 0x55, 0x54, 0xcc, 0xe1, 0xcd, 0x72, 0xeb, 0x77, 0x19, 0x2a,
	0x1d, 0x33, 0xf5, 0xe4, 0x05, 0x94, 0x8f, 0xf8, 0x30, 0x62, 0xe4, 0xc6, 0x80, 0x35, 0xeb, 0x05,
	0xce, 0x1a, 0x93, 0x70, 0x26, 0xd0, 0x99, 0x23, 0x2d, 0x28, 0x9b, 0x5e, 0x91, 0x47, 0xb7, 0x82,
	0xea, 0x38, 0x13, 0x35, 0x9b, 0xda, 0x4a, 0x87, 0xbe, 0x8b, 0x68, 0x07, 0x2a, 0x7a, 0x8a, 0xce,
	0x90, 0xfc, 0x6b, 0xee, 0x26, 0xca, 0xdf, 0x42, 0xf9, 0xa3, 0xc2, 0xf4, 0xe2, 0xff, 0xd4, 0x9b,
	0x00, 0x5d, 0x21, 0x14, 0xf6, 0xc6, 0x7e, 0xf6, 0x83, 0xad, 0x16, 0x0c, 0x03, 0xa7, 0x8a, 0xb6,
	0x61, 0xd5, 0x88, 0x32, 0x8e, 0x3b, 0x96, 0xc8, 0x44, 0xe6, 0x30, 0xab, 0xf6, 0x25, 0x54, 0xde,
	0xab, 0x6c, 0x0c, 0x90, 0x90, 0x62, 0x57, 0x63, 0x36, 0x5d, 0xf1, 0x06, 0x56, 0x4c, 0x40, 0x7b,
	0xee, 0x9d, 0xa4, 0x3b, 0xb0, 0xe6, 0x7e, 0x3e, 0xf9, 0x76, 0x80, 0x72, 0x37, 0x49, 0xe2, 0xc8,
	0xf6, 0xc2, 0xde, 0x17, 0xb3, 0x8c, 0xc0, 0x16, 0xd4, 0xb5, 0xfc, 0x24, 0xc5, 0x84, 0xa6, 0xb8,
	0xcf, 0xd3, 0xde, 0x78, 0x26, 0xdd, 0x76, 0xa1, 0xe3, 0xa1, 0x0a, 0xd0, 0xfc, 0xf6, 0x57, 0xaf,
	0x7c, 0x75, 0xef, 0x4d, 0xd4, 0x1e, 0xc2, 0x63, 0xad, 0x9d, 0x70, 0x6d, 0x35, 0x0b, 0xf6, 0xed,
	0xbd, 0x49, 0x27, 0x0d, 0xec, 0xed, 0xbe, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x13, 0x84, 0x05,
	0x0d, 0xf4, 0x05, 0x00, 0x00,
}
